services:
  inventory-postgres-service:
    image: postgres:latest
    ports:
      - 55433:5432/tcp
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password@1234
      POSTGRES_DB: item_tracking_app
  inventory-mongo-service:
    image: mongo:latest
    ports:
      - 27013:27017/tcp
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password@1234
  inventory-mongo-express-service:
    image: mongo-express:latest
    ports:
      - 8013:8081/tcp
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password@1234
      ME_CONFIG_MONGODB_URL: mongodb://admin:password%401234@inventory-mongo-service:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - inventory-mongo-service
  inventory-serivce:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/kotzakhar/ittrap-inventory-service:latest
    ports:
      - 50003:80
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      ConnectionStrings__PostgreSqlConnection: Host=inventory-postgres-service;Port=5432;Database=item_tracking_app;Username=admin;Password=password@1234
      ConnectionStrings__MongoDbConnection: mongodb://admin:password%401234@inventory-mongo-service:27017
      GlobalConfig__Domain: localhost
      GlobalConfig__JwtPrivateKey: 3CB721B389327EF82A97E47E85298
      GlobalConfig__MediatrLicenseKey: _
    depends_on:
      - inventory-postgres-service
      - inventory-mongo-service
      