apiVersion: apps/v1
kind: Deployment
metadata:
  name: ittrap-identity-service-deployment
spec:
  selector:
    matchLabels:
      app: ittrap-identity-service
  template:
    metadata:
      labels:
        app: ittrap-identity-service
    spec:
      containers:
      - name: ittrap-identity-service
        image: docker.io/kotzakhar/ittrap-identity-service:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_HTTP_PORTS
          value: "80"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: identity-service-config
              key: postgreSqlConnectionString
        - name: GlobalConfig__PasswordPepper
          valueFrom:
            secretKeyRef:
              name: identity-service-config
              key: passwordPepper
        - name: GlobalConfig__Domain
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: domain
        - name: GlobalConfig__JwtPrivateKey
          valueFrom:
            secretKeyRef:
              name: global-config
              key: jwt-private-key
        - name: GlobalConfig__MediatrLicenseKey
          valueFrom:
            secretKeyRef:
              name: global-config
              key: mediatr-license-key
        - name: GlobalConfig__SqsUrl
          valueFrom:
            configMapKeyRef:
              name: identity-service-config
              key: sqs-url
        - name: AWS__Region
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws-default-region
        - name: AWS__ServiceURL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws-service-url
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws-default-region
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-identity-service-nodeport
spec:
  type: NodePort
  selector:
    app: ittrap-identity-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-identity-service
spec:
  type: ClusterIP
  selector:
    app: ittrap-identity-service
  ports:
  - port: 80
    targetPort: 80
