apiVersion: apps/v1
kind: Deployment
metadata:
  name: ittrap-inventory-mongo-service-demployment
spec:
  selector:
    matchLabels:
      app: ittrap-inventory-mongo-service
  template:
    metadata:
      labels:
        app: ittrap-inventory-mongo-service
    spec:
      containers:
      - name: ittrap-inventory-mongo-service
        image: mongo:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: "/secrets/mongo-initdb-root-username"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "/secrets/mongo-initdb-root-password"
        volumeMounts:
        - name: mongo-credentials
          mountPath: /secrets
      volumes:
      - name: mongo-credentials
        secret:
          secretName: inventory-mongo-config
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-inventory-mongo-nodeport
spec:
  type: NodePort
  selector:
    app: ittrap-inventory-mongo-service
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30013
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-inventory-mongo-service
spec:
  type: ClusterIP
  selector:
    app: ittrap-inventory-mongo-service
  ports:
  - port: 27017
    targetPort: 27017
