worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # Common proxy settings
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    server {
        listen 80;

        # Identity service
        location /api/auth/ {
            proxy_pass http://ittrap-identity-service:80;
        }

        # Query service (CQRS read side)
        location /api/v1/query/ {
            proxy_pass http://ittrap-query-service:80;
        }

        # Management service
        location /api/v1/management/ {
            proxy_pass http://ittrap-management-service:80;
        }

        # Inventory service
        location /api/v1/categories/ {
            proxy_pass http://ittrap-inventory-service:80;
        }
        location /api/v1/files/ {
            proxy_pass http://ittrap-inventory-service:80;
        }
        location /api/v1/items/ {
            proxy_pass http://ittrap-inventory-service:80;
        }

        # Location service
        location /api/v1/locations/ {
            proxy_pass http://ittrap-location-service:80;
        }

        # User service
        location /api/v1/users/ {
            proxy_pass http://ittrap-user-service:80;
        }
    }
}
