apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-vault-auth
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-store
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "mongo-eso"
          serviceAccountRef:
            name: eso-vault-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: mongo-config
    creationPolicy: Owner
  data:
    - secretKey: mongo-initdb-root-username
      remoteRef:
        key: mongo
        property: mongo-initdb-root-username
    - secretKey: mongo-initdb-root-password
      remoteRef:
        key: mongo
        property: mongo-initdb-root-password
