apiVersion: apps/v1
kind: Deployment
metadata:
  name: ittrap-email-service-deployment
spec:
  selector:
    matchLabels:
      app: ittrap-email-service
  template:
    metadata:
      labels:
        app: ittrap-email-service
    spec:
      containers:
      - name: ittrap-email-service
        image: docker.io/kotzakhar/ittrap-email-service:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_HTTP_PORTS
          value: "80"
        - name: GlobalConfig__Smtp__Host
          valueFrom:
            secretKeyRef:
              name: email-service-config
              key: host
        - name: GlobalConfig__Smtp__Port
          valueFrom:
            secretKeyRef:
              name: email-service-config
              key: port
        - name: GlobalConfig__Smtp__Username
          valueFrom:
            secretKeyRef:
              name: email-service-config
              key: username
        - name: GlobalConfig__Smtp__Password
          valueFrom:
            secretKeyRef:
              name: email-service-config
              key: password
        - name: GlobalConfig__Smtp__FromEmail
          valueFrom:
            secretKeyRef:
              name: email-service-config
              key: fromEmail
        - name: GlobalConfig__Smtp__FromName
          valueFrom:
            secretKeyRef:
              name: email-service-config
              key: fromName
        - name: GlobalConfig__Smtp__UseSsl
          valueFrom:
            secretKeyRef:
              name: email-service-config
              key: useSsl
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-email-service
spec:
  type: ClusterIP
  selector:
    app: ittrap-email-service
  ports:
  - port: 80
    targetPort: 80
