apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-config
  namespace: ittrap
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: postgres-config
    creationPolicy: Owner
  data:
    - secretKey: postgres-user
      remoteRef:
        key: ittrap/postgres
        property: postgres-user
    - secretKey: postgres-password
      remoteRef:
        key: ittrap/postgres
        property: postgres-password
    - secretKey: postgres-database
      remoteRef:
        key: ittrap/postgres
        property: postgres-database
