apiVersion: v1
kind: Service
metadata:
  name: ittrap-location-postgres-nodeport
spec:
  type: NodePort
  selector:
    app: ittrap-location-postgres-service
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30435
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-location-postgres
spec:
  type: ClusterIP
  selector:
    app: ittrap-location-postgres-service
  ports:
  - port: 5432
    targetPort: 5432
