apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-store
  namespace: ittrap
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "ittrap-eso"
          serviceAccountRef:
            name: eso-vault-auth
