apiVersion: v1
kind: Service
metadata:
  name: ittrap-user-postgres-nodeport
spec:
  type: NodePort
  selector:
    app: ittrap-user-postgres-service
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30436
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-user-postgres
spec:
  type: ClusterIP
  selector:
    app: ittrap-user-postgres-service
  ports:
  - port: 5432
    targetPort: 5432
