services:
  identity-postgres-service:
    image: postgres:latest
    ports:
      - 55432:5432/tcp
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password@1234
      POSTGRES_DB: item_tracking_app
  identity-serivce:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/kotzakhar/ittrap-identity-service:latest
    ports:
      - 55002:80
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      ConnectionStrings__DefaultConnection: Host=identity-postgres-service;Port=5432;Database=item_tracking_app;Username=admin;Password=password@1234
      GlobalConfig__PasswordPepper: MyH0rse1sAm@zing
      GlobalConfig__Domain: localhost
      GlobalConfig__JwtPrivateKey: 3CB721B389327EF82A97E47E85298
      GlobalConfig__AdminEmail: admin@gmail.com
      GlobalConfig__AdminPassword: admin@1234
    depends_on:
      - identity-postgres-service
      