// <auto-generated />
using System;
using Infrastructure.EFPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Categories.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Locations.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Code")
                        .HasColumnType("uuid")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<short>("Floor")
                        .HasColumnType("smallint")
                        .HasColumnName("floor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MovableInstances.MovableInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Code")
                        .HasColumnType("uuid")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<long>("MovableItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("movable_item_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_movable_instances");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_movable_instances_location_id");

                    b.HasIndex("MovableItemId")
                        .HasDatabaseName("ix_movable_instances_movable_item_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_movable_instances_user_id");

                    b.ToTable("movable_instances", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MovableItems.MovableItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("text")
                        .HasColumnName("img_src");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_movable_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_movable_items_category_id");

                    b.ToTable("movable_items", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Permissions.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "users:get"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "users:list"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "users:create"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "users:update"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "users:delete"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "users:reset_password"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "categories:list"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "categories:list_from_node"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "categories:create"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "categories:update"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "categories:delete"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "locations:list"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "locations:get"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "locations:create"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "locations:update"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "locations:delete"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "locations:get_qr_code"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "movable_items:list"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "movable_items:get"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "movable_items:create"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "movable_items:update"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "movable_items:delete"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "movable_instances:list"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "movable_instances:get"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "movable_instances:create"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "movable_instances:delete"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "movable_instances:book"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "movable_instances:cancel_booking"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "movable_instances:assign"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "movable_instances:take_by_code"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "movable_instances:release"
                        },
                        new
                        {
                            Id = 32L,
                            Name = "movable_instances:move"
                        },
                        new
                        {
                            Id = 33L,
                            Name = "movable_instances:get_qr_code"
                        },
                        new
                        {
                            Id = 34L,
                            Name = "users:update_password"
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Roles.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "user"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "manager"
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<byte[]>("_passwordHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("_salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Models.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<long>("PermissionsId")
                        .HasColumnType("bigint")
                        .HasColumnName("permissions_id");

                    b.Property<long>("RolesId")
                        .HasColumnType("bigint")
                        .HasColumnName("roles_id");

                    b.HasKey("PermissionsId", "RolesId")
                        .HasName("pk_roles_permissions");

                    b.HasIndex("RolesId")
                        .HasDatabaseName("ix_roles_permissions_roles_id");

                    b.ToTable("roles_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionsId = 1L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 2L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 3L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 4L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 5L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 6L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 7L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 8L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 9L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 10L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 11L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 12L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 13L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 14L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 15L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 16L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 17L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 18L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 19L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 20L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 21L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 22L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 23L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 24L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 25L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 26L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 27L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 28L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 29L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 30L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 31L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 32L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 33L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 34L,
                            RolesId = 1L
                        },
                        new
                        {
                            PermissionsId = 1L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 2L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 3L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 4L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 5L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 6L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 7L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 8L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 9L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 10L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 11L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 12L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 13L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 14L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 15L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 16L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 17L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 18L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 19L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 20L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 21L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 22L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 23L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 24L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 25L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 26L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 27L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 28L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 29L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 31L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 32L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 33L,
                            RolesId = 3L
                        },
                        new
                        {
                            PermissionsId = 1L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 2L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 7L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 8L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 12L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 13L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 18L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 19L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 23L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 24L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 27L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 28L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 30L,
                            RolesId = 2L
                        },
                        new
                        {
                            PermissionsId = 31L,
                            RolesId = 2L
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<long>("RolesId")
                        .HasColumnType("bigint")
                        .HasColumnName("roles_id");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_users_roles");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_users_roles_users_id");

                    b.ToTable("users_roles", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Categories.Category", b =>
                {
                    b.HasOne("Domain.Aggregates.Categories.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Aggregates.MovableInstances.MovableInstance", b =>
                {
                    b.HasOne("Domain.Aggregates.Locations.Location", "Location")
                        .WithMany("Instances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movable_instances_locations_location_id");

                    b.HasOne("Domain.Aggregates.MovableItems.MovableItem", "MovableItem")
                        .WithMany("Instances")
                        .HasForeignKey("MovableItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movable_instances_movable_items_movable_item_id");

                    b.HasOne("Domain.Aggregates.Users.User", "User")
                        .WithMany("MovableInstances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movable_instances_users_user_id");

                    b.Navigation("Location");

                    b.Navigation("MovableItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Aggregates.MovableItems.MovableItem", b =>
                {
                    b.HasOne("Domain.Aggregates.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movable_items_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Infrastructure.Models.UserSession", b =>
                {
                    b.HasOne("Domain.Aggregates.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Domain.Aggregates.Permissions.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permissions_permissions_permissions_id");

                    b.HasOne("Domain.Aggregates.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permissions_roles_roles_id");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Domain.Aggregates.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_roles_roles_id");

                    b.HasOne("Domain.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_users_users_id");
                });

            modelBuilder.Entity("Domain.Aggregates.Categories.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Aggregates.Locations.Location", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Domain.Aggregates.MovableItems.MovableItem", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("MovableInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
