apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ittrap-dev
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/Kot-Zakhar/item_tracking_app_backend.git
    targetRevision: deployment
    path: deployment/helm/ittrap
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ittrap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
