apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailpit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default

  source:
    repoURL: https://github.com/Kot-Zakhar/item_tracking_app_backend.git
    targetRevision: deployment
    path: deployment/argocd/manifests/mailpit
    directory:
      recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: mailpit
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

