apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-aws-load-balancer-controller
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.7.2
    helm:
      values: |
        clusterName: REPLACE_ME_cluster_name
        region: eu-central-1
        vpcId: REPLACE_ME_vpc_id

        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            # Recommended: create an IRSA role for the controller and put it here.
            eks.amazonaws.com/role-arn: REPLACE_ME_irsa_role_arn
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
